### ISSUE TITLE
DockerComposeBuildArguments MSBuild property not working

### ISSUE THREAD

**Issue by philipwolfe** [microsoft/DockerTools#281]
Hello,
This has been reported in #104 back in 2018, but there has been no action on it.

This code in ...\Microsoft.Docker.Sdk\tools\Microsoft.Docker.dll (Version=2.2.13.1) is wrong.  Here is the code from the DockerComposeClient class.
```csharp
public Task<string> BuildAsync(IEnumerable<string> services, DockerComposeFileSet composeFileSet, bool noCache, DockerDevelopmentMode dockerDevelopmentMode, IDockerLogger logger, string dockerComposeBuildArguments, CancellationToken cancellationToken)
{
  string options = this.BuildDockerComposeOptions(composeFileSet, dockerDevelopmentMode, logger);
  string commandWithArguments = "build" + (noCache ? " --no-cache" : "") + (services != null ? " " + string.Join(" ", services) : "");
 if (!string.IsNullOrWhiteSpace(dockerComposeBuildArguments))
    commandWithArguments = commandWithArguments + " " + dockerComposeBuildArguments;
  return this.ExecuteAsync(options, commandWithArguments, logger, cancellationToken);
}
```

In the code above, the arguments are added AFTER the [SERVICES] when the docs (https://docs.docker.com/compose/reference/build/) specify that any/all options or arguments should added before the [SERVICES].
This doc (https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019#docker-compose-msbuild-properties) says that adding a `DockerComposeBuildArguments` should work, but it does not and I get a build error.
```xml
<DockerComposeBuildArguments>--build-arg configuration="$(Configuration)"</DockerComposeBuildArguments>
```
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(491,5): error DT1001: No such service: --build-arg
```

We really need a fix ASAP or if someone could let me know how they are passing in the build configuration to their Dockerfile in order to perform the `COPY` with the right folder, I would love to know.  
Dockerfile segment:
```
ARG configuration
...
COPY bin/$configuration/ .
```

Thanks.

**Comment by pratiksanglikar** [comment]
Hi @philipwolfe,
Thank you for reporting this bug, we have identified this to be a bug with the tooling and it is added to our backlog.
We will let you know when the fix is available.

**Comment by pratiksanglikar** [comment]
A fix for this bug has been internally implemented. We will let you know when it is available for download.

**Comment by jvitor83** [comment]
@philipwolfe you can workaround this by using the docker-compose build args like:
```yaml
    build:
      context: .
      dockerfile: YourProject/Dockerfile
      args:
        - configuration=Debug
```
and you can create [multiple docker-compose files](https://docs.microsoft.com/pt-br/dotnet/architecture/microservices/multi-container-microservice-net-applications/multi-container-applications-docker-compose#targeting-multiple-environments) to set a configuration for each.
Maybe this can help until the fix is released.

**Comment by dziedrius** [comment]
Although @jvitor83 workaround might work for build arguments, issue is with other commands too - for example "up". You can not use replicas feature of docker compose if you're not using --compatibility arg and using it after the command does not work.

**Comment by derekgreer** [comment]
@jvitor83 I actually arrived here because my docker-compose.yml build args aren't working.   They work fine outside of visual studio.

**Comment by pratiksanglikar** [comment]
@jvitor83 The fix is available to download in the latest preview release [here](https://visualstudio.microsoft.com/vs/preview/).
We will let you know when it becomes available to download in the stable release channel.

**Comment by derekgreer** [comment]
> when the docs (https://docs.docker.com/compose/reference/build/) specify that any/all options or arguments should added before the [SERVICES].

@philipwolfe Just curious, I clicked on the link and can't find the referred verbiage regarding arguments being added.

Here is all I see:

![image](https://user-images.githubusercontent.com/210185/108789000-e8421880-753e-11eb-85c2-326490e33eb2.png)


Can you provide a link to where this documentation is?

**Comment by derekgreer** [comment]
@pratiksanglikar It's unclear from this thread given @pratiksanglikar comment that using build args might work as a work-around.

Would this bug have caused issues with build args specified in docker-compose.yml to not be set properly?

**Comment by pratiksanglikar** [comment]
@derekgreer ,
There is no specific verbiage to indicate that.
If you look at the order in the line - `Usage: build [options] [--build-arg key=val...] [SERVICE...]`
`--build-args key=val...` comes before `[SERVICE...]`

**Comment by derekgreer** [comment]
@pratiksanglikar It sounds like you're answering my first question to @philipwolfe, unless I'm mistaken.

I'm trying to determine if the issue I'm facing with docker-compose.yml not correctly transferring build args to my Dockerfile is related to this bug or whether I should open a new issue.

**Comment by pratiksanglikar** [comment]
@derekgreer Please open a new issue for that.

**Comment by ravipal** [comment]
As per this https://github.com/microsoft/DockerTools/issues/281#issuecomment-783785238 this is fixed.

**Comment by dazinator** [comment]
If this was fixed in Feb 2021, then how come I have this issue using latest VS 2022 professional?

![image](https://user-images.githubusercontent.com/3176632/220606149-1d865f2b-ba12-496d-a7fb-93a5afa374d8.png)

![image](https://user-images.githubusercontent.com/3176632/220606551-0eec71fe-0e21-4791-8910-ef9ef1bc6f6b.png)

![image](https://user-images.githubusercontent.com/3176632/220606738-14565c29-eecb-4748-857c-81a3de569ac9.png)

**Comment by NCarlsonMSFT** [comment]
@dazinator you seem to have put a project property intended for a `.dcproj` in the `.csproj` of your service. Did you mean to use `<DockerfileBuildArguments>--build-arg FEED_ACCESSTOKEN=foobar</DockerfileBuildArguments>`?

**Comment by dazinator** [comment]
@NCarlsonMSFT - what makes you think i've used the property in the `csproj`? The above screenshot with the poprerty group is taken from the `.dcproj` where I have attempted to use that documented property to append a build arg - however when I use it I see this error.

**Comment by NCarlsonMSFT** [comment]
@dazinator Sorry I was not paying enough attention. Seeing a bunch of Docker* properties made me think it was in the service project, but I see not all of the compose propeties have compose in the name.

The error you are getting is from compose and it is b/c you forgot the = between your build arg's name and value:
`<DockerComposeBuildArguments>--build-arg FEED_ACCESSTOKEN=foobar</DockerComposeBuildArguments>`

**Comment by dazinator** [comment]
@NCarlsonMSFT no problem, thank you this was indeed the reason! Doh!
